symbol = {
    "lope": "[\(]",
    "rope": "[\)]",
    "spa": " ",
    "Croke": "\"",
    "corn": "\:",
    "commie": "\,",
    "underscore": "_",
    "langle": "[<]",
    "rangle": "[>]",
    "punk": ".",
    "equals": "=",
    "equal": "=",
    "lick": "[\[]",
    "rick": "[\]]",
    "lip": "[\{]",
    "rip": "[\}]",
}

alphabet = {
    "adam": "[aA]",
    "bravo": "[bB]",
    "charlie": "[cC]",
    "delta": "[dD]",
    "echo": "[eE]",
    "foxtrot": "[fF]",
    "gamma": "[gG]",
    "hotel": "[hH]",
    "india": "[iI]",
    "juliet": "[jJ]",
    "kilo": "[kK]",
    "lima": "[lL]",
    "mike": "[mM]",
    "nancy": "[nN]",
    "oscar": "[oO]",
    "papa": "[pP]",
    "queen": "[qQ]",
    "romeo": "[rR]",
    "soy": "[sS]",
    "tango": "[tT]",
    "uniform": "[uU]",
    "victor": "[vV]",
    "whiskey": "[wW]",
    "x-ray": "[xX]",
    "yellow": "[yY]",
    "zebra": "[zZ]",
}

tokens = dict(symbol.items() + alphabet.items())